In [3]:
import pandas as pd
from datasets import get_dataset, nombres_datasets

In [4]:
nombres_datasets

['01_original',
 '01_producto_estrella',
 '01_productos_todos',
 '01_por_cliente',
 '01_120',
 '02_original',
 '02_producto_estrella',
 '02_productos_todos',
 '02_por_cliente',
 '02_precios_cuidados',
 '02_120',
 'maestro_productos',
 '02_productos_todos_anti_leak',
 '02_120_anti_leak',
 '02_stocks_productos_todos',
 '02_stocks_anti_leak',
 '02_productos_todos_anti_leak_con_FE_04',
 '02_productos_todos_anti_leak_con_FE_06',
 '02_productos_desglosado_crudo',
 '02_productos_desglosado']

In [5]:
df_desglosado = get_dataset("02_productos_desglosado")
df_desglosado

,periodo,customer_id,product_id,cust_request_qty,cust_request_tn,tn,product_category,cat2,cat3,brand,sku_size,plan_precios_cuidados
0,201701,10001,20480,6.0,0.85598,0.85598,PC,CABELLO,ACONDICIONADOR,SHAMPOO1,750.0,0
1,201701,10001,20482,1.0,0.75874,0.75874,PC,CABELLO,SHAMPOO,CAPILATIS,400.0,0
2,201701,10001,20483,0.0,0.00000,0.00000,PC,CABELLO,SHAMPOO,SHAMPOO3,10.0,0
3,201701,10001,20484,6.0,0.89664,0.89664,PC,DEOS,Aero,DEOS3,100.0,0
4,201701,10001,20485,2.0,0.73612,0.73612,HC,VAJILLA,Gel,MUSCULO,300.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
19109368,201912,10582,20474,0.0,0.00000,0.00000,PC,CABELLO,ACONDICIONADOR,SHAMPOO1,400.0,0
19109369,201912,10582,20476,0.0,0.00000,0.00000,PC,PIEL2,Jabon Barra,SHAMPOO2,125.0,0
19109370,201912,10582,20477,0.0,0.00000,0.00000,HC,VAJILLA,Gel,MUSCULO,300.0,0
19109371,201912,10582,20478,0.0,0.00000,0.00000,HC,HOGAR,PISOS,MUSCULO,750.0,0
19109372,201912,10582,20479,0.0,0.00000,0.00000,HC,PROFESIONAL,Gel,MUSCULO,2000.0,0

In [6]:
# group df_desglosado by "periodo" and "customer_id", sum cust_request_qty, cust_request_tn and tn columns and discard the rest
df_desglosado_agrupado = df_desglosado.groupby(["periodo", "customer_id"]).sum()[["cust_request_qty", "cust_request_tn", "tn"]]
df_desglosado_agrupado

                     cust_request_qty  cust_request_tn          tn
periodo customer_id
201701  10001                  4013.0       2567.40529  2543.89944
        10002                 14680.0       3208.66180  3143.64478
        10003                  8182.0       2459.14864  2425.98913
        10004                  5606.0       1797.92975  1738.91838
        10005                  7001.0       1063.86071  1058.82526
...                               ...              ...         ...
201912  10633                     0.0          0.00000     0.00000
        10634                     0.0          0.00000     0.00000
        10635                     0.0          0.00000     0.00000
        10636                     0.0          0.00000     0.00000
        10637                     0.0          0.00000     0.00000

[21492 rows x 3 columns]

In [8]:
df_desglosado_agrupado.to_csv("./datasets/02_sellout_agrupado_por_cliente.csv")